eureka:
    client:
        serviceUrl:
            #服务注册中心地址
            defaultZone: http://localhost:8101/eureka/
spring:
    application:
        #应用名称
        name: tbay-system-config-server
    profiles:
        #使用本地属性文件
        active: native
    cloud:
        config:
            server:
                native:
                    #属性文件地址，只要指定文件夹的路径
                    search-locations: classpath:/properties/
server:
    port: 8201